version: "3"
services:
  mssql:
    container_name: guest_book_db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "GuestBook42Pass"
      
  rabbitmq:
    container_name: guest_book_rabbitmq
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

  storage_service:
    container_name: guest_book_service
    build:
      context: .
      dockerfile: Dockerfile.storage-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_started

  web_api:
    container_name: guest_book_web_api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:443"
      - "5000:80"
    depends_on:
      storage_service:
        condition: service_started
    