version: "3"
services:
  mssql:
    container_name: guest_book_db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "GuestBook42Pass"
      
  rabbitmq:
    container_name: guest_book_rabbitmq
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    